services:
  - type: web
    name: game-bar-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: MAIN_BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: DATABASE_URL
        sync: false